# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-seo-tag]

# Permalinks
permalink:        pretty

# Setup
title:            "Arturo Gutiérrez"
subtitle:         "Android and iOS Software Engineer"
tagline:          "Blog"
description:      "Learn Android advanced topics with articles and examples. Material Design, MVP, Kotlin, Clean Architecture, RxJava."
url:              http://arturogutierrez.com
baseurl:          /
future:           true
logo:             /public/images/avatar.jpg

author:
  name:           'Arturo Gutiérrez'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/arturogutierrez/arturogutierrez.github.io

 # Social Media Content
twitter:
  username: arturogdg
github:
  username: arturogutierrez
linkedin:
  username: arturogutierrezdiazguerra
