# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Arturo Gutiérrez
tagline:          "Arturo's technical blog" 
description:      "Android and iOS Software Engineer"
url:              http://arturogutierrez.com
baseurl:          /
future:           true

author:
  name:           'Arturo Gutiérrez'
  url:            https://twitter.com/arturogdg

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/arturogutierrez/arturogutierrez.github.io

 # Social Media Content
twitter_username: arturogdg
github_username:  arturogutierrez
linkedin_username: arturogutierrezdiazguerra
